name: Weekly Build and Test (1.8.1EOL)

on:
  push:
    branches:
      - main
  schedule:
    # - cron: "0 1 * * 1"
    
    
jobs:
  build-linux:
    runs-on: ubuntu-latest   
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Initiate conda channels
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: testenv
        python-version: 3.8
        channels: conda-forge,bioconda
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true
        use-only-tar-bz2: true
          
    - name: Set up environment
      run: |
        conda create --name testenv python=3.8
        source activate testenv
    - name: Install Dependencies
      run: |
        source activate testenv
        conda install -y -c bioconda vsearch==2.21.1
        conda install -y -c conda-forge hmmer==3.1b2
        conda install -y -c bioconda bbmap==38.69
        conda install biopython
        pip install pyzstd
        pip install pytest

        git clone -b 1.8.1-EOL git@github.com:USDA-ARS-GBRU/itsxpress.git --single-branch
        cd itsxpress
        pip install .
    - name: Test with pytest
      run: |
        source activate testenv
        pytest
